import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('user').del();

  // Inserts seed entries
  await knex('user').insert([
    {
      user_name: 'KN',
      user_phone: '91234567',
      notes: '過敏：嚴重的花生過敏。需遠離所有堅果製品。',
      emerg_name: 'Peter',
      emerg_phone: '93456789',
      emerg_relation: '父母',
      emerg_address: '香港快樂谷主街123號蘭花峰7樓5A室',
    },
    {
      user_name: 'Peter',
      user_phone: '93456789',
      notes: '多發性硬化症：多發性硬化症。行動受限和疲勞。',
      emerg_name: 'KN',
      emerg_phone: '97890123',
      emerg_relation: '孩子',
      emerg_address: '香港尖沙咀柏景大道456號金塔15樓20B室',
    },
    {
      user_name: 'Tevin',
      user_phone: '97890123',
      notes: '糖尿病：1型糖尿病。需要注射胰島素。',
      emerg_name: 'Della',
      emerg_phone: '91234560',
      emerg_relation: '朋友',
      emerg_address: '香港半山山道789號山景大廈25樓3C室',
    },
    {
      user_name: 'Vivian',
      user_phone: '91234560',
      notes: '哮喘：根據需要使用吸入劑治療哮喘發作。',
      emerg_name: 'Roy',
      emerg_phone: '94567890',
      emerg_relation: '伴侶',
      emerg_address: '香港淺水灣海景徑101號海濤居3樓8室',
    },
    {
      user_name: 'Roy',
      user_phone: '94567890',
      notes: '心臟狀況：有心臟跳動的病史。不可進行負擔過大的活動。',
      emerg_name: 'Vivian',
      emerg_phone: '96789012',
      emerg_relation: '伴侶',
      emerg_address: '香港西貢日落台222號日落灣6樓12室',
    },
    {
      user_name: 'Brano',
      user_phone: '96789012',
      notes: '癲癇：癲癇發作。發作期間不可壓制。',
      emerg_name: 'Katy',
      emerg_phone: '91234568',
      emerg_relation: '親戚',
      emerg_address: '香港愉景灣花園路333號碼頭花園10樓18D室',
    },
    {
      user_name: 'Evan',
      user_phone: '91234568',
      notes: '血友病：血友病B。避免危險的活動。',
      emerg_name: 'Grace',
      emerg_phone: '92123456',
      emerg_relation: '朋友',
      emerg_address: '香港北角海灣大廈444號海景大廈22樓25B室',
    },
    {
      user_name: 'Hung',
      user_phone: '92123456',
      notes: '腹瀉病：腹瀉不耐症。只能食用無麩質的食物。',
      emerg_name: 'Susan',
      emerg_phone: '93456781',
      emerg_relation: '伴侶',
      emerg_address: '香港上環堅尼地城堅尼道555號濱江大廈5樓7A室',
    },
    {
      user_name: 'Susan',
      user_phone: '93456781',
      notes: '乳糖不耐症：乳糖不耐症。不可食用乳製品。',
      emerg_name: 'Hung',
      emerg_phone: '95678901',
      emerg_relation: '伴侶',
      emerg_address: '香港山頂山頂道666號峰景大廈40樓30室',
    },
    {
      user_name: 'Grace',
      user_phone: '95678901',
      notes: '焦慮症：廣泛性焦慮症。可能會發生恐慌發作。',
      emerg_name: 'Evan',
      emerg_phone: '98901234',
      emerg_relation: '朋友',
      emerg_address: '香港堅尼地城楓樹街777號楓葉閣8樓9C室',
    },
    {
      user_name: 'Beeno',
      user_phone: '98901234',
      notes: '偏頭痛：頻繁的偏頭痛。發作期間需調暗燈光並休息。',
      emerg_name: 'Janice',
      emerg_phone: '91234576',
      emerg_relation: '親戚',
      emerg_address: '香港銅鑼灣露台道888號珍珠大廈12樓14D室',
    },
    {
      user_name: 'Chloe',
      user_phone: '91234576',
      notes: '視力受損：法定盲人。需要協助導航。',
      emerg_name: 'Eric',
      emerg_phone: '92345678',
      emerg_relation: '兄弟姐妹',
      emerg_address: '香港大埔竹林路999號竹園閣1樓2室',
    },
    {
      user_name: 'Kasey',
      user_phone: '92345678',
      notes: '行動受限：使用輪椅。需要使用無障礙通道。',
      emerg_name: 'Alex',
      emerg_phone: '94567812',
      emerg_relation: '朋友',
      emerg_address: '香港香港仔松樹里111號松柏苑4樓16室',
    },
    {
      user_name: 'Della',
      user_phone: '94567812',
      notes: '自體免疫性疾病：紅斑狼瘡。對陽光敏感，關節疼痛。',
      emerg_name: 'Tevin',
      emerg_phone: '96789034',
      emerg_relation: '朋友',
      emerg_address: '香港荃灣蕨岡庭222號蕨峰閣9樓6B室',
    },
    {
      user_name: 'Katy',
      user_phone: '96789034',
      notes: '甲狀腺問題：甲狀腺功能低下。正在服用甲狀腺藥物。',
      emerg_name: 'Brano',
      emerg_phone: '91234509',
      emerg_relation: '親戚',
      emerg_address: '香港西灣河珊瑚道333號珊瑚花園7樓21C室',
    },
    {
      user_name: 'Eric',
      user_phone: '91234509',
      notes: 'COPD：慢性阻塞性肺病。按照指示使用吸入劑。',
      emerg_name: 'Chloe',
      emerg_phone: '92123457',
      emerg_relation: '兄弟姐妹',
      emerg_address: '香港灣仔蘭花廣場444號薔薇大廈18樓10室',
    },
    {
      user_name: 'Janice',
      user_phone: '92123457',
      notes: '腎臟疾病：慢性腎臟病。監測液體攝入量。',
      emerg_name: 'Beeno',
      emerg_phone: '91234567',
      emerg_relation: '親戚',
      emerg_address: '香港油麻地翠綠道555號翡翠峰14樓8室',
    },
    {
      user_name: 'Alex',
      user_phone: '99123456',
      notes: '關節炎：類風濕性關節炎。關節疼痛和僵硬。',
      emerg_name: 'Kasey',
      emerg_phone: '90123456',
      emerg_relation: '朋友',
      emerg_address: '香港旺角鑽石街666號鑽石大廈27樓22D室',
    },
  ]);
}
